-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 20:19:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema medico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema medico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medico` DEFAULT CHARACTER SET utf8 ;
USE `medico` ;

-- -----------------------------------------------------
-- Table `medico`.`CITA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medico`.`CITA` (
  `hora` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medico`.`MÉDICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medico`.`MÉDICO` (
  `codmed` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `CITA_fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codmed`, `CITA_fecha`),
  INDEX `fk_MÉDICO_CITA_idx` (`CITA_fecha` ASC) VISIBLE,
  CONSTRAINT `fk_MÉDICO_CITA`
    FOREIGN KEY (`CITA_fecha`)
    REFERENCES `medico`.`CITA` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medico`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medico`.`PACIENTE` (
  `codpac` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `CITA_fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codpac`, `CITA_fecha`),
  INDEX `fk_PACIENTE_CITA1_idx` (`CITA_fecha` ASC) VISIBLE,
  CONSTRAINT `fk_PACIENTE_CITA1`
    FOREIGN KEY (`CITA_fecha`)
    REFERENCES `medico`.`CITA` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
