-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 20:15:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema departamento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema departamento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `departamento` DEFAULT CHARACTER SET utf8 ;
USE `departamento` ;

-- -----------------------------------------------------
-- Table `departamento`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `departamento`.`EMPLEADO` (
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_ingreso` VARCHAR(45) NOT NULL,
  `num_emp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_emp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `departamento`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `departamento`.`DEPARTAMENTO` (
  `num_depto` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `presupuesto` VARCHAR(45) NOT NULL,
  `num_emp` VARCHAR(45) NOT NULL,
  `EMPLEADO_num_emp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_depto`, `nombre`, `num_emp`),
  INDEX `fk_DEPARTAMENTO_EMPLEADO_idx` (`EMPLEADO_num_emp` ASC) VISIBLE,
  CONSTRAINT `fk_DEPARTAMENTO_EMPLEADO`
    FOREIGN KEY (`EMPLEADO_num_emp`)
    REFERENCES `departamento`.`EMPLEADO` (`num_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
