-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 20:14:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema poliza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poliza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poliza` DEFAULT CHARACTER SET utf8 ;
USE `poliza` ;

-- -----------------------------------------------------
-- Table `poliza`.`DE AUTOMOVIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliza`.`DE AUTOMOVIL` (
  `matricula` INT NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poliza`.`POLIZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliza`.`POLIZA` (
  `numero` INT NOT NULL,
  `fecha_inicial` VARCHAR(45) NOT NULL,
  `fehca_fin` VARCHAR(45) NOT NULL,
  `DE AUTOMOVIL_matricula` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_POLIZA_DE AUTOMOVIL1_idx` (`DE AUTOMOVIL_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_POLIZA_DE AUTOMOVIL1`
    FOREIGN KEY (`DE AUTOMOVIL_matricula`)
    REFERENCES `poliza`.`DE AUTOMOVIL` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poliza`.`DE VIDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliza`.`DE VIDA` (
  `numero` INT NOT NULL,
  `POLIZA_numero` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_DE VIDA_POLIZA1_idx` (`POLIZA_numero` ASC) VISIBLE,
  CONSTRAINT `fk_DE VIDA_POLIZA1`
    FOREIGN KEY (`POLIZA_numero`)
    REFERENCES `poliza`.`POLIZA` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poliza`.`VIVIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliza`.`VIVIENDA` (
  `domicilio` INT NOT NULL,
  `POLIZA_numero` INT NOT NULL,
  INDEX `fk_VIVIENDA_POLIZA1_idx` (`POLIZA_numero` ASC) VISIBLE,
  CONSTRAINT `fk_VIVIENDA_POLIZA1`
    FOREIGN KEY (`POLIZA_numero`)
    REFERENCES `poliza`.`POLIZA` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poliza`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poliza`.`table1` (
  `dn1` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` VARCHAR(45) NOT NULL,
  `DE VIDA_numero` INT NOT NULL,
  PRIMARY KEY (`dn1`),
  INDEX `fk_table1_DE VIDA_idx` (`DE VIDA_numero` ASC) VISIBLE,
  CONSTRAINT `fk_table1_DE VIDA`
    FOREIGN KEY (`DE VIDA_numero`)
    REFERENCES `poliza`.`DE VIDA` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
