-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 20:16:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema profesor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema profesor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `profesor` DEFAULT CHARACTER SET utf8 ;
USE `profesor` ;

-- -----------------------------------------------------
-- Table `profesor`.`PROFESOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profesor`.`PROFESOR` (
  `cod-profesor INT` INT NOT NULL,
  `nif` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod-profesor INT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profesor`.`GRUPO ALUMNOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profesor`.`GRUPO ALUMNOS` (
  `cod-grupo` INT NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod-grupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profesor`.`P-G`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profesor`.`P-G` (
  `año-academico` INT NOT NULL,
  `PROFESOR_cod-profesor INT` INT NOT NULL,
  `GRUPO ALUMNOS_cod-grupo` INT NOT NULL,
  INDEX `fk_P-G_PROFESOR_idx` (`PROFESOR_cod-profesor INT` ASC) VISIBLE,
  INDEX `fk_P-G_GRUPO ALUMNOS1_idx` (`GRUPO ALUMNOS_cod-grupo` ASC) VISIBLE,
  CONSTRAINT `fk_P-G_PROFESOR`
    FOREIGN KEY (`PROFESOR_cod-profesor INT`)
    REFERENCES `profesor`.`PROFESOR` (`cod-profesor INT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P-G_GRUPO ALUMNOS1`
    FOREIGN KEY (`GRUPO ALUMNOS_cod-grupo`)
    REFERENCES `profesor`.`GRUPO ALUMNOS` (`cod-grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
